# =================================
# PROJECT'S GENERAL SITE SETTINGS #
# =================================

PROJECT_HOME_PATH_ROOT = ENV['HOME'] + '/web-apps/zagruz/'
PROJECT_HOME_PATH_GENERAL = PROJECT_HOME_PATH_ROOT + '.general/'

if(Rails.env.production? || Rails.env.staging?)
	PROJECT_SITE_URL_HOST = 'сайт.рф' # URL of the entire project's main host with welcome page
	PROJECT_SITE_URL_WITH_SSL_PROTOCOL = 'https://' + PROJECT_SITE_URL_HOST

	ENABLE_METRIKA = true
	ENABLE_RECAPTCHA = true

else
	PROJECT_SITE_URL_HOST = 'some.dev-site.lan' # URL of the entire project's main welcome page
	PROJECT_SITE_URL_WITH_SSL_PROTOCOL = 'http://' + PROJECT_SITE_URL_HOST

	ENABLE_METRIKA = false
	ENABLE_RECAPTCHA = false
end

PROJECT_SITE_URL_WITH_PROTOCOL = 'http://' + PROJECT_SITE_URL_HOST
PROJECT_SITE_CABINET_URL_ROOT  = '//cabinet.' + PROJECT_SITE_URL_HOST
SERVICE_AUTH_URL_ROOT          = '//auth.' + PROJECT_SITE_URL_HOST

SITE_PATH_ADDRESS_ROOT = '//' + PROJECT_SITE_URL_HOST
SITE_PATH_ADDRESS_ROOT_CANONICAL = SITE_PATH_ADDRESS_ROOT

SITE_WWW_ADDRESS_ROOT    = SITE_PATH_ADDRESS_ROOT
SITE_STATIC_ADDRESS_ROOT = SITE_PATH_ADDRESS_ROOT

SERVICE_AUTH_URL_AUTHORIZE  = SERVICE_AUTH_URL_ROOT + '/oauth/authorize'
SERVICE_AUTH_URL_GET_TOKEN  = SERVICE_AUTH_URL_ROOT + '/oauth/token'
SERVICE_AUTH_URL_SIGN_OUT   = SERVICE_AUTH_URL_ROOT + '/logout_all'

JWT_OWN_NEEDS_OAUTH_TOKEN_MAX_LENGTH = 448
JWT_OWN_NEEDS_OAUTH_TOKEN_SCOPES_MAX_LENGTH = 128

JWT_OAUTH_TOKEN_LIFETIME_READ         = 2.hours
JWT_OAUTH_TOKEN_LIFETIME_WRITE        = 10.minutes
JWT_OAUTH_TOKEN_LIFETIME_IMPEXP       = 20.minutes
JWT_OAUTH_TOKEN_LIFETIME_MONEY_ADMIN  = 7.minutes

PROJECT_RESTRICTED_AREA_GENERAL   = 1
PROJECT_RESTRICTED_AREA_ECOMMERCE = 2
PROJECT_RESTRICTED_AREA_ECOMMERCE_SELLERS = 3
PROJECT_RESTRICTED_AREA_ADMIN     = 4

## =================================================================

SITE_EMAIL_DOMAIN = 'dmon.ru'
SITE_EMAIL_SUPPORT_TEAM = 'support@dmon.ru'

SITE_PROJECT_NAME_ENG = 'Project'

SAFE_UID_PAYDOCUMENT_SHOP_ID = 'DOK' # Shop ID for Documents

MARKETPLACE_MODE_ONLINE_SHOP = true

NO_CONFIRMATION_GRACE_PERIOD = 2.days # период, когда действует не подтверждённый аккаунт (email)
NO_CONFIRMATION_GRACE_POSTS_LIMIT = 3
NO_CONFIRMATION_SKIP_TIME_SHIFT = 20.seconds


PRODUCT_IMAGE_MAX_FILE_COUNT = 5
PRODUCT_IMAGE_UPLOAD_MAX_FILE_SIZE = 500.kilobytes

## =================================================================


# DEPRECATED:
SITE_PATH_ADDRESS = PROJECT_SITE_URL_HOST
SITE_PATH_ADDRESS_WITH_PROTOCOL = PROJECT_SITE_URL_WITH_PROTOCOL
SITE_PATH_ADDRESS_WITH_SSL_PROTOCOL = PROJECT_SITE_URL_WITH_SSL_PROTOCOL
# ----------------