source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Support for Cross-Origin Resource Sharing (CORS) to allow cross domain AJAX calls without using workarounds such as JSONP.
# NGINX do it better.
# gem 'rack-cors', :require => 'rack/cors'

# Databases
gem 'pg'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
#gem 'active_model_serializers', '~> 0.10.0'


# Internationalization
# gem 'unicode_utils'
# gem 'rails-i18n'
# gem 'ru_propisju'
# gem 'russian'
#gem 'route_translator'
#gem 'http-accept'

# Detect GeoPosition by IP
# gem 'maxmind_geoip2'

# User Interface
gem 'bootstrap', '4.0.0.beta'
gem 'popper_js' # Needs for bootstrap dropdown
gem 'tether-rails' # A positioning engine to make overlays, tooltips and dropdowns better
gem 'jquery-rails' # Use jquery as the JavaScript library

# Some Addons
gem 'slim-rails' # slim-rails doesn't work with ckeditor correctly, in that case use only gem 'slim', without overriding ERB.
gem 'recaptcha' # Google ReCaptcha
gem 'xxhash'
gem 'browser'

# Authorization gems
#gem 'oauth2'
gem 'devise'
gem 'devise-i18n'
gem "devise_invitable"
gem 'pundit'
#gem 'pundit_namespaces'
gem 'omniauth'
gem 'omniauth-vkontakte'
gem 'omniauth-yandex'
gem 'omniauth-odnoklassniki'
gem 'omniauth-mail_ru'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
#gem 'vkontakte_api'
#gem "switch_user"

# Own OAuth2 Authorization
gem 'doorkeeper'
gem 'doorkeeper-jwt'
gem 'doorkeeper-i18n'
# gem 'devise-doorkeeper'


# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'rspec-rails', '~> 3.6'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  
  gem 'simplecov', :require => false
  
  # Generate fake data
  gem 'faker'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  
  # gem 'mina', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
